# Generated by Django 3.2 on 2022-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='share_equity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shares',
            name='share_value',
            field=models.FloatField(),
        ),
    ]
