# Generated by Django 3.2 on 2022-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_category_project_shares_alter_business_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mandatory_filling',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=20),
        ),
    ]
