# Generated by Django 3.2 on 2022-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20220701_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='share_equity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='share_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
