# Generated by Django 3.2 on 2022-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220701_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='share_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
